apiVersion: v1
kind: Service
metadata:
  name: {{ include "smartbox.fullname" . }}
  labels:
    {{- include "smartbox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  {{- with .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "smartbox.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 8088
      targetPort: 8088
