apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smartbox.fullname" . }}
  labels:
    {{- include "smartbox.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "smartbox.selectorLabels" . | nindent 6 }}
  {{- with .Values.strategy }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .maxSurge }}
      maxUnavailable: {{ .maxUnavailable }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "smartbox.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if include "smartbox.serviceAccountName" . }}
      serviceAccountName: {{ include "smartbox.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.image.digest }}
          image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "smartbox.fullname" . }}-config
            - secretRef:
                name: {{ include "smartbox.secretName" . }}
          {{- with .Values.probe }}
          livenessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ .port }}
              scheme: {{ .scheme | default "HTTP" }}
            {{- with .liveness }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ .port }}
              scheme: {{ .scheme | default "HTTP" }}
            {{- with .readiness }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
